// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as util$0 from "../util/models.js";

export class RecordInfo {
    "uuid": string;
    "fileName": string;
    "size": number;
    "sizeStr": string;
    "create": util$0.Datetime | null;
    "modify": util$0.Datetime | null;

    /** Creates a new RecordInfo instance. */
    constructor($$source: Partial<RecordInfo> = {}) {
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("sizeStr" in $$source)) {
            this["sizeStr"] = "";
        }
        if (!("create" in $$source)) {
            this["create"] = null;
        }
        if (!("modify" in $$source)) {
            this["modify"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): RecordInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecordInfo($$parsedSource as Partial<RecordInfo>);
    }
}
