// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function DocList(): Promise<string[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3028887424) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function FileContent(fileName: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1761704901, fileName) as any;
    return $resultPromise;
}

export function SyncFile(fileName: string, content: string): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1211937091, fileName, content) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
