// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class License {
    "deviceId": string;
    "content": string;
    "type": string;

    /** Creates a new License instance. */
    constructor($$source: Partial<License> = {}) {
        if (!("deviceId" in $$source)) {
            this["deviceId"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new License instance from a string or object.
     */
    static createFrom($$source: any = {}): License {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new License($$parsedSource as Partial<License>);
    }
}
